// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// count_negative
IntegerVector count_negative(SEXP namefile_);
RcppExport SEXP Reviews_count_negative(SEXP namefile_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type namefile_(namefile_SEXP);
    rcpp_result_gen = Rcpp::wrap(count_negative(namefile_));
    return rcpp_result_gen;
END_RCPP
}
// count_positive
IntegerVector count_positive(SEXP namefile_);
RcppExport SEXP Reviews_count_positive(SEXP namefile_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type namefile_(namefile_SEXP);
    rcpp_result_gen = Rcpp::wrap(count_positive(namefile_));
    return rcpp_result_gen;
END_RCPP
}
// get_vocab
StringVector get_vocab(SEXP namefile_);
RcppExport SEXP Reviews_get_vocab(SEXP namefile_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type namefile_(namefile_SEXP);
    rcpp_result_gen = Rcpp::wrap(get_vocab(namefile_));
    return rcpp_result_gen;
END_RCPP
}
